create table if not exists public.deals (
  id bigint generated by default as identity primary key,
  title text not null,
  price text not null,
  merchant text not null,
  url text not null,
  image text,
  tags text[] default '{}',
  featured boolean default false,
  created_at timestamp with time zone default now()
);

create table if not exists public.clicks (
  id bigint generated by default as identity primary key,
  deal_id bigint references public.deals(id) on delete set null,
  merchant text,
  url text not null,
  created_at timestamp with time zone default now()
);

alter table public.deals enable row level security;
alter table public.clicks enable row level security;

do $$ begin
  if not exists (select 1 from pg_policies where tablename='deals' and policyname='Deals are readable by anon') then
    create policy "Deals are readable by anon" on public.deals for select using (true);
  end if;
  if not exists (select 1 from pg_policies where tablename='clicks' and policyname='Clicks are readable by anon') then
    create policy "Clicks are readable by anon" on public.clicks for select using (true);
  end if;
end $$;
